{% set name = "psy-reg" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}{% if environ.get("BUILD_STR_END") %}_{{ environ.get("BUILD_STR_END") }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 27]

requirements:
  build:
  - python
  - pip
  run:
  - python
  - psyplot
  - psy-simple
  - statsmodels
  - scipy

test:
  requires:
    - pytest
    - codecov
    - pytest-cov >=2.6.1
    - psy-simple
    - dask
    - pyqt  # [osx]
    - netcdf4
    - seaborn
  imports:
    - psy_reg
    - psy_reg.plotters
  source_files:
    - tests
  commands:
    - pytest -v --cov=psy_reg
    - codecov

about:
  home: https://github.com/psyplot/psy-reg
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualizing and calculating regression plots

  description: |
    This psyplot plugin can be used to make fits to your data and visualize
    them
  doc_url: http://psyplot.readthedocs.io/projects/psy-reg
dev_url: https://github.com/psyplot/psy-reg
