name: psyplot_docs
channels:
    - local
    - psyplot/label/master
    - conda-forge
dependencies:
    - python=3.8
    - dask
    - netCDF4
    - seaborn
    - ipython
    - sphinx
    - sphinx_rtd_theme
    - psy-reg
    - autodocsumm
    - pip
